#############################################################################
# Makefile for building: 3DTransformations_lab
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sun Dec 16 14:49:46 2012
# Project:  3DTransformations_lab.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile 3DTransformations_lab.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Isrc -Isrc/lib -Isrc/math -Isrc/support -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/settings.cpp \
		src/mainwindow.cpp \
		src/main.cpp \
		src/glwidget.cpp \
		src/databinding.cpp \
		src/target.cpp \
		src/particleemitter.cpp \
		src/lib/targa.cpp \
		src/lib/glm.cpp \
		src/support/resourceloader.cpp moc_mainwindow.cpp \
		moc_glwidget.cpp \
		moc_databinding.cpp \
		qrc_images.cpp
OBJECTS       = settings.o \
		mainwindow.o \
		main.o \
		glwidget.o \
		databinding.o \
		target.o \
		particleemitter.o \
		targa.o \
		glm.o \
		resourceloader.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		moc_databinding.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		3DTransformations_lab.pro
QMAKE_TARGET  = 3DTransformations_lab
DESTDIR       = 
TARGET        = 3DTransformations_lab

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 3DTransformations_lab.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile 3DTransformations_lab.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile 3DTransformations_lab.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/3DTransformations_lab1.0.0 || $(MKDIR) .tmp/3DTransformations_lab1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/3DTransformations_lab1.0.0/ && $(COPY_FILE) --parents src/vector.h src/settings.h src/mainwindow.h src/glwidget.h src/databinding.h src/camera.h src/target.h src/particleemitter.h src/lib/targa.h src/lib/glm.h src/math/vector.h src/support/resourceloader.h .tmp/3DTransformations_lab1.0.0/ && $(COPY_FILE) --parents textures/images.qrc .tmp/3DTransformations_lab1.0.0/ && $(COPY_FILE) --parents src/settings.cpp src/mainwindow.cpp src/main.cpp src/glwidget.cpp src/databinding.cpp src/target.cpp src/particleemitter.cpp src/lib/targa.cpp src/lib/glm.cpp src/support/resourceloader.cpp .tmp/3DTransformations_lab1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui .tmp/3DTransformations_lab1.0.0/ && (cd `dirname .tmp/3DTransformations_lab1.0.0` && $(TAR) 3DTransformations_lab1.0.0.tar 3DTransformations_lab1.0.0 && $(COMPRESS) 3DTransformations_lab1.0.0.tar) && $(MOVE) `dirname .tmp/3DTransformations_lab1.0.0`/3DTransformations_lab1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/3DTransformations_lab1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp moc_databinding.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp moc_databinding.cpp
moc_mainwindow.cpp: src/settings.h \
		src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: src/camera.h \
		src/vector.h \
		src/particleemitter.h \
		src/common.h \
		src/target.h \
		src/glwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/glwidget.h -o moc_glwidget.cpp

moc_databinding.cpp: src/databinding.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/databinding.h -o moc_databinding.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: textures/images.qrc \
		textures/beyonceface.tga \
		textures/beyonce_singleladies_dance.jpg \
		textures/beyonce_teeth.jpg \
		textures/beyonceface.jpg \
		textures/beyonceface.png \
		textures/particle1.bmp \
		textures/beyonceface.bmp \
		textures/particle2.bmp \
		textures/particle3.jpg
	/usr/bin/rcc -name images textures/images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		src/glwidget.h \
		src/camera.h \
		src/vector.h \
		src/particleemitter.h \
		src/common.h \
		src/target.h
	/usr/bin/uic-qt4 src/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

settings.o: src/settings.cpp src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o src/settings.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/settings.h \
		ui_mainwindow.h \
		src/glwidget.h \
		src/camera.h \
		src/vector.h \
		src/particleemitter.h \
		src/common.h \
		src/target.h \
		src/databinding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

main.o: src/main.cpp src/mainwindow.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

glwidget.o: src/glwidget.cpp src/glwidget.h \
		src/camera.h \
		src/vector.h \
		src/particleemitter.h \
		src/common.h \
		src/target.h \
		src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o src/glwidget.cpp

databinding.o: src/databinding.cpp src/databinding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databinding.o src/databinding.cpp

target.o: src/target.cpp src/target.h \
		src/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o target.o src/target.cpp

particleemitter.o: src/particleemitter.cpp src/particleemitter.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particleemitter.o src/particleemitter.cpp

targa.o: src/lib/targa.cpp src/lib/targa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o targa.o src/lib/targa.cpp

glm.o: src/lib/glm.cpp src/lib/glm.h \
		src/lib/targa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glm.o src/lib/glm.cpp

resourceloader.o: src/support/resourceloader.cpp src/support/resourceloader.h \
		src/lib/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourceloader.o src/support/resourceloader.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_databinding.o: moc_databinding.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databinding.o moc_databinding.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

